version: '2'
services:
  dev:
    build: .
    image: keboola/my-component
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - KBC_TOKEN
      - KBC_TEST_TOKEN
      - KBC_URL
      - KBC_TEST_URL
      - KBC_TEST_BUCKET